require 'json'
require 'fileutils'

# Resolve react_native_pods.rb
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})',
  __dir__
]).strip

require_relative '../node_modules/react-native-permissions/scripts/setup.rb'

platform :ios, '16.0'
use_frameworks! :linkage => :static
prepare_react_native_project!

setup_permissions([
  'Camera',
  'LocationWhenInUse',
  'PhotoLibrary',
  'LocationAlways',
  'Notifications',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage
  use_frameworks! :linkage => linkage.to_sym
end

target 'OutdoorServiceBooking' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,

  )

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => true

  # RNFB pods (no manual versioning needed, will use podspec)
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'RNFBRemoteConfig', :path => '../node_modules/@react-native-firebase/remote-config'
  pod 'RNFBML', :path => '../node_modules/@react-native-firebase/ml'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        config.build_settings['SWIFT_VERSION'] = '5.0'
        # config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        config.build_settings['SWIFT_VERIFY_EMITTED_MODULE_INTERFACE'] = 'NO'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['ENABLE_PREVIEWS'] = 'NO'
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end

      # Remove duplicate ReactCommon.modulemap
      if target.name == 'React-RCTAppDelegate'
        target.build_phases.each do |phase|
          next unless phase.respond_to?(:files) && phase.files
          phase.files.each do |file|
            if file.display_name.include?("ReactCommon.modulemap")
              phase.remove_file_reference(file.file_ref)
            end
          end
        end
      end
    end
  end
end
