default_platform(:ios)

platform :ios do
  desc "Submit a new build to Firebase App Distribution"
  lane :distribute do
    # Authenticate with Apple Store Connect
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"].gsub("\\n", "\n"),
      duration: 1200,
      in_house: false
    )

    # Fetch certificates and provisioning profiles
    get_certificates(api_key: api_key)
    get_provisioning_profile(api_key: api_key, ad_hoc: true)

    # build_app handles the compilation and export of the IPA
    build_app(
      scheme: "RNBoilerplate",
      workspace: "RNBoilerplate.xcworkspace",
      configuration: "Release",
      export_method: "ad-hoc",
      output_directory: "build/ios/ipa",
      output_name: "RNBoilerplate.ipa",
      clean: true,
      export_options: {
        method: "ad-hoc",
        compileBitcode: false,
        uploadBitcode: false
      }
    )
    
    upload_to_firebase
  end

  desc "Upload existing build to Firebase"
  lane :upload_to_firebase do |options|
    firebase_app_distribution(
      app:  "1:577882676291:ios:9297ddde469c74f8ad48f6",
      groups: "testing-group",
      ipa_path: options[:ipa_path] || "build/ios/ipa/RNBoilerplate.ipa",
      release_notes: "Standard iOS distribution via Fastlane"
    )
  end
end
